### PR TITLE
[CPAN PRC] A bunch of mostly cosmetic changes

### PR DESCRIPTION
**Pull request by JJ**
Main one is probably adding `.travis.yml` for continuous integration. None touches the code itself. All address issues which I previously created.

### CODE REVIEW

**Comment by estrabd** [comment]
@JJ thanks! I am happy to see that this module/util is getting some PRC love. Would you do me a favor and squash the travis ci commits? After that I see no reason to not accept this PR.

**Comment by JJ** [comment]
Sure. Will do.  Thanks for getting back to me so fast.

**Comment by JJ** [comment]
Done already. There's an additional commit trying to deal with the CPANTS
issues, which actually seem to be only about using Dist::Zilla. Anyway, I
can look into them and if there's anything else you want me to do, like
adding a test for unmerged PR, just let me know.

**Comment by neilb** [comment]
:+1:

**Comment by JaderDias** [comment]
@estrabd could you review this Pulll Request again?

**Comment by estrabd** [comment]
Thanks, sorry for the extreme delay @JaderDias  and @neilb ! Merging.

**Pull request merged**
