### PR TITLE
Address issue #36

### PR DESCRIPTION
**Pull request by SilentScope**

### CODE REVIEW

**Comment by SilentScope** [comment]
Some silly mistake of mine :S

**Comment by SilentScope** [comment]
Now it is not possible to run the script so would be great to fix and release as soon as possible...

**Comment by estrabd** [comment]
Please add a regression test to this PR per https://github.com/aspiers/mysqldiff/blob/master/CONTRIBUTING.md, especially since you didn't create a test in the first place.  I'll give you a few days, after that I will revert your entire change a make a new release. Thank you.

**Comment by SilentScope** [comment]
Please do not revert - I will add integration tests

**Comment by SilentScope** [comment]
Added integration test. Successfully ran all tests on my machine.

**Comment by estrabd** [comment]
Thank you.

**Pull request merged**
