### PR TITLE
issue #40 - should drop FKs before indexes and create FKs after indexes

### PR DESCRIPTION
**Pull request by coofercat**
This patch changes the order of DROPs so that FKs get dropped before indexes (because indexes can't be dropped if the FKs depend on them). Adding FKs remains where it always was (at the end).

### CODE REVIEW

**Comment by estrabd** [comment]
Hi will you please add/update a unit test for this? I require this as part of the contribution policy. Thanks!

Brett

**Comment by estrabd** [comment]
@coofercat are you going to add/update a unit test for this? Thanks.

**Comment by coofercat** [comment]
Sorry for the delay - I'll take a look and see what I can do for a test...

**Comment by estrabd** [comment]
@coofercat - any ideas? One idea is to just ensure that there is a test for that code path which works the same both before an after your change.

**Comment by estrabd** [comment]
@coofercat, I know it has been a while, but any chance you could update the tests to exercise your changes and look for regressions?

**Pull request merged**
